services:

  wordpress:
    container_name: wordpress
    build:
      context: wordpress
      args:
        wpimage: ${DOCKER_WORDPRESS_IMAGE}
    environment:
      WORDPRESS_DB_HOST: ${WORDPRESS_DB_HOST}
      WORDPRESS_DB_USER: ${WORDPRESS_DB_USER}
      WORDPRESS_DB_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      WORDPRESS_DB_NAME: ${WORDPRESS_DB_NAME}
      WORDPRESS_DEBUG: ${WORDPRESS_DEBUG}
      WORDPRESS_THEME_NAME: ${WORDPRESS_THEME_NAME}
      WORDPRESS_TABLE_PREFIX: wp_
      WORDPRESS_CONFIG_EXTRA: |
        define('WP_ENVIRONMENT_TYPE', 'development');
        define('WP_DEVELOPMENT_MODE', 'theme');
    volumes:
      - ./wp-content:/var/www/html/wp-content
      - wp_html:/var/www/html
      - type: bind
        source: ./composer.json
        target: /var/www/html/composer.json
    ports:
      - 8000:80
    restart: always
    depends_on:
      - db


  db:
    container_name: mariadb
    image: ${DOCKER_DB_IMAGE}
    environment:
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_DATABASE: ${WORDPRESS_DB_NAME}
      MYSQL_USER: ${WORDPRESS_DB_USER}
      MYSQL_PASSWORD: ${WORDPRESS_DB_PASSWORD}
      MYSQL_ROOT_HOST: ${MYSQL_ROOT_HOST}
    ports:
      - "3306"
    restart: always
    volumes:
      - db_data:/var/lib/mysql
    # quieter log output from mysql, shhhh
    command: --general-log=0 --log-error

  phpmyadmin:
    depends_on:
      - db
    image: ${DOCKER_DB_GUI_IMAGE}
    container_name: phpmyadmin
    restart: always
    ports:
      - 8080:80
    environment:
      PMA_HOST: db
      MYSQL_USERNAME: ${WORDPRESS_DB_USER}
      MYSQL_ROOT_PASSWORD: ${WORDPRESS_DB_PASSWORD}


volumes:
  wp_html:
  db_data:
